# Generated by Django 5.2.4 on 2025-08-03 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.FileField(upload_to='call_recordings/')),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('TRANSCRIBING', 'Transcribing'), ('TRANSCRIBED', 'Transcribed'), ('EXTRACTING_INFO', 'Extracting Information'), ('READY_FOR_REVIEW', 'Ready for Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('TRANSCRIPTION_FAILED', 'Transcription Failed'), ('EXTRACTION_FAILED', 'Information Extraction Failed')], default='UPLOADED', max_length=50)),
                ('transcript_text', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('service_interest', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_timestamp', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('raw_llm_output', models.JSONField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_extractions', to=settings.AUTH_USER_MODEL)),
                ('call_recording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_info', to='agents.callrecording')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('service_purchased', models.TextField(blank=True, null=True)),
                ('onboard_date', models.DateField(auto_now_add=True)),
                ('original_extraction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_client_record', to='agents.extractedclientinfo')),
            ],
        ),
    ]
