# Generated by Django 5.2.4 on 2025-07-31 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecording',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('TRANSCRIBING', 'Transcribing'), ('TRANSCRIBED', 'Transcribed'), ('EXTRACTING_INFO', 'Extracting Information'), ('READY_FOR_REVIEW', 'Ready for Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('TRANSCRIPTION_FAILED', 'Transcription Failed'), ('EXTRACTION_FAILED', 'Information Extraction Failed')], default='UPLOADED', max_length=50),
        ),
        migrations.CreateModel(
            name='ExtractedClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('service_interest', models.TextField(blank=True, null=True)),
                ('deal_size_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_timestamp', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('raw_llm_output', models.JSONField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_extractions', to=settings.AUTH_USER_MODEL)),
                ('call_recording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_info', to='agents.callrecording')),
            ],
        ),
    ]
