# Generated by Django 5.2.4 on 2025-07-31 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_callrecording_status_extractedclientinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('service_purchased', models.TextField(blank=True, null=True)),
                ('deal_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('onboard_date', models.DateField(auto_now_add=True)),
                ('original_extraction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_client_record', to='agents.extractedclientinfo')),
            ],
        ),
    ]
