# Generated by Django 5.2.4 on 2025-08-02 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='deal_size',
        ),
        migrations.RemoveField(
            model_name='extractedclientinfo',
            name='deal_size_estimate',
        ),
    ]
